name: Konnektid Devlog
description: Konnektid Devlog
meta_description: "For all the nerdy stuff you won't find on our regular blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://konnektid.github.io'

disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://konnektid.github.io'
author:         'Konnektid'
authorTwitter:  '@konnektid'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
